### ISSUE TITLE
"Creating a new recipe" test gives wrong value for params

### ISSUE THREAD

**Issue by wwboyer** [learn-co-curriculum/sinatra-restful-routes-lab#17]
The rspec file contains the following test:
```Ruby
describe "creating a new recipe" do 
    before do 
      params = {
        "name" => "pumpkin pie",
        "ingredients" => "pumpkin, flour, butter, sugar",
        "cook_time" => "1 hour"
      }

      post '/recipes', params
      follow_redirect!
    end
    it "creates a new recipe and saves to the database" do 
      expect(Recipe.all.count).to eq(3)
      expect(Recipe.last.name).to eq("pumpkin pie")
    end

    it "redirects to the recipe show page" do 
      expect(last_request.url).to include("/recipes/#{Recipe.last.id}")
    end
  end
```

However, it sets `params` equal to only the hash 
```Ruby
      {
        "name" => "pumpkin pie",
        "ingredients" => "pumpkin, flour, butter, sugar",
        "cook_time" => "1 hour"
      }
```
rather than a properly formatted nested `params` hash, such as 
```Ruby
{
  "recipes" =>  {
    "name" => "pumpkin pie",
    "ingredients" => "pumpkin, flour, butter, sugar",
    "cook_time" => "1 hour"
  }
}
```

Therefore, in order to pass the test, one would have to provide an answer such as `Recipe.create(params)`, which is counterintuitive to how we've been taught to format a `params` hash.

**Comment by DanielSeehausen** [comment]
Hi @wwboyer. Thank you for bringing this to our attention. For the scope and purposes of this lab, which only has one controller and model, making the params nested opens the question of whether we are gaining anything while we are increasing complexity.

If this has manifested in some issue, or is breaking with a version of Sinatra you are using, please let me know. Otherwise, if you feel this deserves further discussion, please re-open the issue with additional supporting material.

--- 

Hi there,

I'm having difficulty reproducing the issue, so I'm going to close it for now.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙
