### ISSUE TITLE
Passing the tests even though my form/post route do not match up

### ISSUE THREAD

**Issue by bmcilhenny** [learn-co-curriculum/sinatra-restful-routes-lab#18]
Passed tests without the correct name tag in my form. 

My new.erb file should not have been passing given the recipe in the name fields below. 
`<!DOCTYPE html>
<html>
  <head>
  </head>
  <body>
    <h1>Make your Recipe Card!</h1>
    <form action="/recipes" method="post">
        Recipe Name: <input id="name" type="text" name="recipe[name]">
        Recipe Ingredients: <input id="ingredients" type="text" name="recipe[ingredients]">
        Recipe Cook Time: <input id="cook_time" type="text" name="recipe[cook_time]">
      <input type="submit" value="submit" name="submit">
    </form>
  </body>
</html>
`

And here is the corresponding post route:

`  post '/recipes' do
    @recipe = Recipe.create(name: params['name'], ingredients: params['ingredients'], cook_time: params['cook_time'])
    redirect "/recipes/#{@recipe.id}"
  end`

To work correctly in the browser the name:, ingredient: and cook_time: values need to also have the recipe[whatever], it does not work in the browser with this setup and yet I still pass the tests

**Comment by DanielSeehausen** [comment]
Hi there @bmcilhenny. Thank you for bringing this to our attention. After running your code, I was unable to reproduce the issue :(. I would suggest revisiting your code, as well as considering the shorter: `@recipe = Recipe.create(params)` syntax!. Please let me know if there is something I am missing. 

Raising issues on GitHub should be reserved for problems with the curriculum — not difficulties solving a lab.

The issue here appears to be with your own code. If the error messages in the test suite are not providing enough information for you to diagnose the problem, try the following three things:

Run your code as it is intended to be run. That is, don't simply rely on the test suite to check the functionality of your code — check it yourself! For Ruby code, add some lines to the bottom of the file that call your methods and output verifiable information to the terminal. For Sinatra or Rails applications, fire up your local server and try executing the same actions that the test suite is failing to complete. For JavaScript code, open up your browser's JS console, paste in your code, and play around with your functions and variables.
Use Pry to poke around your Ruby (or Sinatra), Rails, or JavaScript code step-by-step. Check that the values of particular variables are what you expect them to be at various points throughout the program's execution.
Use the Ask a Question (AAQ) feature, where the Technical Coaches (on supported tracks) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out this helpful article in the Learn Help Center.
If, after reviewing your code and consulting AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 💙
