### ISSUE TITLE
third lab that wont allow migrate

### ISSUE THREAD

**Issue by alouiscious** [learn-co-curriculum/sinatra-restful-routes-lab#29]
I worked with yet another tc session was need to resolve a lab that cloned, but its file were too outdated to migrate the required database.

Also for db issues Have you tried deleting the db file and re-running the migrations? Also try rake db:rollback STEP=5, then do rake db:migrate If that doesn't work delete your db file (probably ending in .sqlite) and run migrate again.
User avatar
Tao Liu 8 MINUTES AGO
Sure
Renee Sims 2 MINUTES AGO
thanks deleted the db folder and had to reinstall activerecord 5.1 and sqlite3 ~> 1.3.13.

unfortunately, the lab loaded active record 4.2.5  and sequel 1.3.6 which would not run.

**Comment by sgharms** [comment]
@alouiscious This lab, in `master` [doesn't seem to have any migrations](https://github.com/learn-co-curriculum/sinatra-restful-routes-lab/tree/2e18568b2624425e1bc68232d6bed967cabfe679/db).

I don't _think_ this issue is opened on the correct repository. Could you please open an issue on the repository that shows this behavior? I know we've recently updated a number of labs to get around this version conflict behavior, and I'd like to get them all closed out.
